services:
  traefik:
    image: traefik:v3.2
    ports:
      - 3000:80
      - 8081:8080
    restart: unless-stopped
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - ./apps/web/src:/app/apps/web/src
    depends_on:
      - files
      - auth
    labels:
      traefik.enable: true
      traefik.http.routers.web-app.entrypoints: web
      traefik.http.routers.web.rule: PathPrefix(`/`) && !PathPrefix(`/api/auth`) && !PathPrefix(`/api/files`)
      traefik.http.services.web-app.loadbalancer.server.port: 3000

  auth:
    build:
      args:
        - WORKSPACE_ROOT=services
        - WORKSPACE_NAME=auth
      context: .
      dockerfile: ./Dockerfile
    env_file: ./services/auth/.env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=80
      # only for development
      - AUTH_JWT_KEY_ID=26f8fdd64024c34c1268510d3dcab8f1
      - AUTH_JWT_PRIVATE_KEY=f14ceb56e9790f3cdf6ce4c251f07868975bc4ec414f171195098ccc91100f2b
    volumes:
      - ./services/auth/src:/app/services/auth/src
      - .pnpm-store:/app/.pnpm-store
    labels:
      traefik.enable: true
      traefik.http.routers.auth.entrypoints: web
      traefik.http.routers.auth.rule: PathPrefix(`/api/auth`)
      traefik.http.services.auth.loadbalancer.server.port: 80
      traefik.http.middlewares.auth-strip.stripprefix.prefixes: /api/auth
      traefik.http.routers.auth.middlewares: auth-strip

  files: 
    build:
      args:
        - WORKSPACE_ROOT=services
        - WORKSPACE_NAME=files
      context: .
      dockerfile: ./Dockerfile
    env_file: ./services/files/.env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=80
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_CRED_ACCESS_KEY_ID=minioadmin
      - S3_CRED_SECRET_ACCESS_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
      - AUTH_SERVER_URL=http://auth
    volumes:
      - ./services/files/src:/app/services/files/src
      - .pnpm-store:/app/.pnpm-store
    labels:
      traefik.enable: true
      traefik.http.routers.file.entrypoints: web
      traefik.http.routers.file.rule: PathPrefix(`/api/files`)
      traefik.http.services.file.loadbalancer.server.port: 80
      traefik.http.middlewares.files-strip.stripprefix.prefixes: /api/files
      traefik.http.routers.file.middlewares: files-strip

  # this service is for local s3 development 
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - .minio-data:/data

volumes:
  .minio-data:
  .pnpm-store:
