services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - ./apps/web/src:/app/apps/web/src
    ports:
      - '3000:3000'
    depends_on:
      - files
      - auth

  auth: 
    build:
      args:
        - WORKSPACE_ROOT=services
        - WORKSPACE_NAME=auth
      context: .
      dockerfile: ./Dockerfile
    env_file: ./services/auth/.env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./services/auth/src:/app/services/auth/src
      - .pnpm-store:/app/.pnpm-store

  files: 
    build:
      args:
        - WORKSPACE_ROOT=services
        - WORKSPACE_NAME=files
      context: .
      dockerfile: ./Dockerfile
    env_file: ./services/files/.env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=80
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_CRED_ACCESS_KEY_ID=minioadmin
      - S3_CRED_SECRET_ACCESS_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
    ports:
      - "8081:80"
    volumes:
      - ./services/files/src:/app/services/files/src
      - .pnpm-store:/app/.pnpm-store

  # this service is for local s3 development 
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - .minio-data:/data

volumes:
  .minio-data:
  .pnpm-store:
